# Generated by Django 3.1.2 on 2020-11-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
