# Generated by Django 3.1.2 on 2020-11-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20201129_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='id',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='id',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='codigo_servicio',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
