# Generated by Django 3.1.2 on 2020-11-30 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_servicio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.servicio'),
        ),
    ]
