# Generated by Django 3.1.2 on 2020-11-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_reserva_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='url',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
