# Generated by Django 3.1.2 on 2020-11-30 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_auto_20201130_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='url',
        ),
    ]
