# Generated by Django 3.1.2 on 2020-11-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_remove_servicio_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='apell_cliente',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='cant_personas',
            new_name='Cantidad_de_personas',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='celu_cliente',
            new_name='Celular',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='nom_cliente',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='servicio',
            new_name='Servicio',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_evento',
            new_name='fecha_del_evento',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='total',
        ),
    ]
