# Generated by Django 3.1.2 on 2020-11-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_auto_20201130_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
    ]
