# Generated by Django 3.1.2 on 2020-11-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_auto_20201130_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='Comentarios',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
