# Generated by Django 3.1.2 on 2020-11-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_auto_20201130_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
