# Generated by Django 3.1.2 on 2020-12-01 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_auto_20201130_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='image',
        ),
    ]
