# Generated by Django 3.1.2 on 2020-12-01 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0018_remove_servicio_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='nom_servicio',
            new_name='Tipo_de_servicio',
        ),
    ]
