# Generated by Django 3.1.2 on 2020-12-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0019_auto_20201201_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='Tipo_de_servicio',
            new_name='nom_servicio',
        ),
    ]
